### ISSUE TITLE
Utilizing Ichigo Without Self-Training

### ISSUE THREAD

**Issue by ruidazeng** [janhq/ichigo#107]
Is it possible to implement Ichigo in my projects without undergoing the model training process myself? If so, are there pre-trained models or resources available to facilitate this? For instance, I came across the [llama3-s-base-v0.2 model](https://huggingface.co/homebrewltd/llama3-s-base-v0.2) on Hugging Face. Can similar pre-trained models be used with Ichigo?

**Comment by tikikun** [comment]
It's really not possible because Ichigo in itself is an end to end training process.
