### ISSUE TITLE
feat: Ichigo from semantics to sound tokens

### ISSUE THREAD

**Issue by tikikun** [janhq/ichigo#108]
## Problem
Currently Ichigo sort-of relying on TTS

## Description
Directly sound decoder token, reduce even further the latency

**Comment by hahuyhoang411** [comment]
MaskGCT:
VRAM Usage: 10GB
Synthetic voice:
AVG time: 40s for 20s of synthetic voice (1 A6000)
Semantic tokens: Model (8192 codebook, max size 749): 10s audio = 479 semantic tokens 

Code to get
```
def get_semantic_token_ids(reference_path):
    """
    Extract semantic token IDs from an input audio file using MaskGCT Pipeline.
    
    Args:
        reference_path (str): Path to the input audio file
        
    Returns:
        list: List of semantic token IDs
    """
    global semantic_model, semantic_codec, codec_encoder, codec_decoder
    global t2s_model, s2a_model_1layer, s2a_model_full, semantic_mean, semantic_std
    
    # Process audio similar to voice_clone function
    prompt_wav_path = process_audio(reference_path, max_duration=15)
    
    # Check if models need to be loaded
    if is_gpu_memory_over_limit():
        print("Loading models due to GPU memory limit")
        (
            semantic_model, semantic_codec, codec_encoder, codec_decoder,
            t2s_model, s2a_model_1layer, s2a_model_full, semantic_mean, semantic_std,
            whisper_model, whisper_pipe
        ) = load_model()

    print("Processing audio for semantic tokens:", prompt_wav_path)
    
    try:
        # Create pipeline instance
        pipeline = MaskGCT_Inference_Pipeline(
            semantic_model,
            semantic_codec,
            codec_encoder,
            codec_decoder,
            t2s_model,
            s2a_model_1layer,
            s2a_model_full,
            semantic_mean,
            semantic_std,
            device
        )
        
        # Load and process audio
        speech_16k = librosa.load(prompt_wav_path, sr=16000)[0]
        
        # Extract features using pipeline's processor
        input_features, attention_mask = pipeline.extract_features(speech_16k)
        
        # Move tensors to device
        input_features = input_features.unsqueeze(0).to(device)
        attention_mask = attention_mask.unsqueeze(0).to(device)
        
        # Extract semantic codes using pipeline
        semantic_tokens, _ = pipeline.extract_semantic_code(
            input_features, 
            attention_mask
        )
        
        # Convert tokens to list of IDs
        token_ids = semantic_tokens.squeeze().cpu().numpy().tolist()
        
        return token_ids
        
    except Exception as e:
        print(f"Error during semantic token extraction: {e}")
        return None

# Make sure models are loaded
if semantic_model is None or semantic_codec is None:
    (
        semantic_model, semantic_codec, codec_encoder, codec_decoder,
        t2s_model, s2a_model_1layer, s2a_model_full, semantic_mean, semantic_std,
        whisper_model, whisper_pipe
    ) = load_model()

# Get semantic token IDs
reference_path = "/maskgct_earth.wav"
token_ids = get_semantic_token_ids(reference_path)

if token_ids is not None:
    print(f"Number of tokens: {len(token_ids)}")
    print(f"token IDs: {token_ids}")
```

**Comment by PodsAreAllYouNeed** [comment]
> MaskGCT: VRAM Usage: 10GB Synthetic voice: https://drive.google.com/drive/u/2/folders/1H5wnXuFWEz6RixMrCCTMKQ_naGBKh1Of AVG time: 40s for 20s of synthetic voice (1 A6000) Semantic tokens: Model (8192 codebook, max size 749): 10s audio = 479 semantic tokens
> 
> Code to get
> 
> ```
> def get_semantic_token_ids(reference_path):
>     """
>     Extract semantic token IDs from an input audio file using MaskGCT Pipeline.
>     
>     Args:
>         reference_path (str): Path to the input audio file
>         
>     Returns:
>         list: List of semantic token IDs
>     """
>     global semantic_model, semantic_codec, codec_encoder, codec_decoder
>     global t2s_model, s2a_model_1layer, s2a_model_full, semantic_mean, semantic_std
>     
>     # Process audio similar to voice_clone function
>     prompt_wav_path = process_audio(reference_path, max_duration=15)
>     
>     # Check if models need to be loaded
>     if is_gpu_memory_over_limit():
>         print("Loading models due to GPU memory limit")
>         (
>             semantic_model, semantic_codec, codec_encoder, codec_decoder,
>             t2s_model, s2a_model_1layer, s2a_model_full, semantic_mean, semantic_std,
>             whisper_model, whisper_pipe
>         ) = load_model()
> 
>     print("Processing audio for semantic tokens:", prompt_wav_path)
>     
>     try:
>         # Create pipeline instance
>         pipeline = MaskGCT_Inference_Pipeline(
>             semantic_model,
>             semantic_codec,
>             codec_encoder,
>             codec_decoder,
>             t2s_model,
>             s2a_model_1layer,
>             s2a_model_full,
>             semantic_mean,
>             semantic_std,
>             device
>         )
>         
>         # Load and process audio
>         speech_16k = librosa.load(prompt_wav_path, sr=16000)[0]
>         
>         # Extract features using pipeline's processor
>         input_features, attention_mask = pipeline.extract_features(speech_16k)
>         
>         # Move tensors to device
>         input_features = input_features.unsqueeze(0).to(device)
>         attention_mask = attention_mask.unsqueeze(0).to(device)
>         
>         # Extract semantic codes using pipeline
>         semantic_tokens, _ = pipeline.extract_semantic_code(
>             input_features, 
>             attention_mask
>         )
>         
>         # Convert tokens to list of IDs
>         token_ids = semantic_tokens.squeeze().cpu().numpy().tolist()
>         
>         return token_ids
>         
>     except Exception as e:
>         print(f"Error during semantic token extraction: {e}")
>         return None
> 
> # Make sure models are loaded
> if semantic_model is None or semantic_codec is None:
>     (
>         semantic_model, semantic_codec, codec_encoder, codec_decoder,
>         t2s_model, s2a_model_1layer, s2a_model_full, semantic_mean, semantic_std,
>         whisper_model, whisper_pipe
>     ) = load_model()
> 
> # Get semantic token IDs
> reference_path = "/maskgct_earth.wav"
> token_ids = get_semantic_token_ids(reference_path)
> 
> if token_ids is not None:
>     print(f"Number of tokens: {len(token_ids)}")
>     print(f"token IDs: {token_ids}")
> ```

This pipeline is a little inefficient
1. input_features, attention_mask can be cached
2. pipeline.extract_semantic_code only needs 2 models. Semantic_codec and semantic_model. The rest of the models aren't necessary. easier to just replicate the [function](https://github.com/open-mmlab/Amphion/blob/afc7308ddc1bc27d16a16b7e0cdc9e1b2dfc33f6/models/tts/maskgct/maskgct_utils.py#L110C1-L121C39), rather than load the whole pipeline.

In fact, everything up to extract_semantic can be preloaded for the reference speech.

At inference, we can fine-tune ichigo or train an adapter to eliminate the need for this step, leaving us with only the semantic-to-acoustic and acoustic-codec steps. But in any case I can see why this is slow and requires alot of memory overall. The rest of the other steps are all also diffusion models

**Comment by tikikun** [comment]
in favor of f5-tts
