### ISSUE TITLE
planning: Ichigo Decoder

### ISSUE THREAD

**Issue by PodsAreAllYouNeed** [janhq/ichigo#111]
# Goal
Replace existing TTS cascade with a speech decoder that directly generates speech. This change will replace the current TTS cascade which adds latency to ichigo's response time.

# Potential Solutions
 - [Llama-Omni](https://arxiv.org/pdf/2409.06666) uses an upsampling-decoder-vocoder pipeline to generate speech
 - MaskGCT (slow)
 - Find some method to reuse WhisperSpeech which is already a TTS model. But it needs to be fine-tunned to our desired single speaker, with high quality generation.

**Comment by tikikun** [comment]
In light of recent development on f5-tts, we can consider slow down on this end temporarily since f5-tts can pretty much helped us accomplish what we need

**Comment by hahuyhoang411** [comment]
As discussed, We will use F5tts.
