### ISSUE TITLE
Some Question about the technology report.

### ISSUE THREAD

**Issue by handsomelys** [janhq/ichigo#132]
## Problem
Some Question about the technology report.

## Description
In chapter 3.2.4 Noise Audio Data, “We then employed the Qwen2.5-72B model [Team, 2024b] to generate diverse synthetic
answers for those inaudible inputs” How do you understand this sentence?

## Hypotheses
Does it mean that the randomly arranged discrete tokens of WhisperVQ are converted into audio files and then input into Qwen2.5-72B? As far as I know, only Qwen-audio in the Qwen series has the ability to process audio, right?

## Next Steps
Looking forward to your reply :)

**Comment by tikikun** [comment]
Hi it just means in order to respond to an in-audible inputs we need to have data of how it would respond to, for example


user: <random noise>

ai: Sorry, i couldn't catch that.....  (generated by qwen)

**Comment by tikikun** [comment]
we will update this in reviewed paper

**Comment by handsomelys** [comment]
> Hi it just means in order to respond to an in-audible inputs we need to have data of how it would respond to, for example
> 
> user:
> 
> ai: Sorry, i couldn't catch that..... (generated by qwen)

Thank you for your reply. But I still have a question. According to the report, you used Qwen2.5-72b to synthesize the data. What is the data type input to Qwen2.5? Is it an audio file? But can Qwen2.5 process audio? As far as I know, only Qwen-audio in the Qwen series can do audio understanding?

**Comment by bachvudinh** [comment]
@handsomelys Qwen2.5 is used to generate answer to noise audio only, no audio input here. I just input prompt to Qwen2.5 to make it generate diverse answer as possible.

**Comment by handsomelys** [comment]
> @handsomelys Qwen2.5 is used to generate answer to noise audio only, no audio input here. I just input prompt to Qwen2.5 to make it generate diverse answer as possible.

Thanks for your reply, I roughly understand. But what does "prompt" mean here? Is it a single text prompt that makes qwen2.5 generate some answers that refuse to respond to the inaudible input you synthesized (even though these inaudible files are not input to qwen2.5)?

**Comment by bachvudinh** [comment]
> > @handsomelys Qwen2.5 is used to generate answer to noise audio only, no audio input here. I just input prompt to Qwen2.5 to make it generate diverse answer as possible.
> 
> Thanks for your reply, I roughly understand. But what does "prompt" mean here? Is it a single text prompt that makes qwen2.5 generate some answers that refuse to respond to the inaudible input you synthesized (even though these inaudible files are not input to qwen2.5)?

prompt is just text, something like please generate diverse answer with overall content is refuse to response to noise audio from user.
