### ISSUE TITLE
chore: Whisper model demo

### ISSUE THREAD

**Issue by tikikun** [janhq/ichigo#147]
## Goal
- We need a simple demo for our newly trained whisper model, to validate model quality, to try it out before using for Ichigo training

## Description
- Gradio probably

**Comment by bachvudinh** [comment]
- I make a simple demo using Gradio. Compare output from our model (whisper medium + ichigo quantizer) to whisper medium on ASR task.
- The UI will look like this:  
 ![image](https://github.com/user-attachments/assets/cf29e5c9-6f7e-49f8-809e-75c95913673e)

**Comment by bachvudinh** [comment]
closed by this PR.
