### ISSUE TITLE
feat: New architecture for end-to-end audio training

### ISSUE THREAD

**Issue by tikikun** [janhq/ichigo#29]

**Comment by tikikun** [comment]
maybe we need to prioritize improve encoder

**Comment by 0xSage** [comment]
@tikikun can you elaborate a bit on this? What architecture are you envisioning.

**Comment by tikikun** [comment]
This is pending, because we do not have enough data and resources to carry out end-to-end training (both for code change and data storage will be quite tremendous). We will revise it once resourcing is a bit less tight.

**Comment by tikikun** [comment]
hand-over to @PodsAreAllYouNeed

**Comment by tikikun** [comment]
We must close this ticket since it's no longer valid
- We changed the sound generation model which does not need codebook lookup
- We double down on quantizer layers
