### ISSUE TITLE
planning: Ichigo Encoder

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/ichigo#92]
## Goal

- Paralinguistic emotions: emotions, i.e. acoustic encoder
- We are using a semantic encoder i.e. WhisperVQ, so acoustic tokens are lost
- Parallel tokens, WaveLM
- Need to have a target

**Comment by hahuyhoang411** [comment]
Good papers for this topic: 
1. https://arxiv.org/abs/2402.05755
2. https://arxiv.org/abs/2402.12226
