### ISSUE TITLE
planning: Ichigo v0.4 Speech Enhancements

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/ichigo#93]
## Goal 

- Baseline enhancements, i.e. noise reduction
- Processing step: pre-model before Ichigo

**Comment by tikikun** [comment]
should we use current speech enhancement tech to tackle this instead of developing our own?

**Comment by tikikun** [comment]
@PodsAreAllYouNeed we can icebox this if this is not priority

**Comment by tikikun** [comment]
also cc @dan-homebrew

**Comment by PodsAreAllYouNeed** [comment]
Speech Enhancement is also included in the VADHandler proposed in #91

**Comment by hahuyhoang411** [comment]
Mark as done and start to work on v0.5

**Comment by FerLuisxd** [comment]
> Mark as done and start to work on v0.5

Is this done?
