### ISSUE TITLE
feat: fast open source tts for ichigo

### ISSUE THREAD

**Issue by PodsAreAllYouNeed** [janhq/ichigo#94]
We need to replace the current fishspeech with better TTS model.

WIP Shortlist of Possible candidates:
- Amphion (https://github.com/open-mmlab/Amphion) <-this is a framework
- Tacotron2 (https://github.com/NVIDIA/tacotron2)
- Hifi-GAN (https://github.com/jik876/hifi-gan)
- MELLE (https://arxiv.org/pdf/2407.08551)
- VALLE-2 (https://arxiv.org/pdf/2406.05370)
- Voicebox (https://arxiv.org/pdf/2306.15687)
- F5-TTS (https://arxiv.org/pdf/2410.06885)
- CosyVoice (https://github.com/FunAudioLLM/CosyVoice)

Test sentence: 
I'm Ichigo, a local AI created by Homebrew Research. I'm here to help answer your questions and make your life easier.

Samples
https://drive.google.com/drive/folders/1FbR5H7rqirHDgxbjxO8Zwhxsj5y4t_mq?usp=sharing

| Name | License | Code | Paper | Comments |
|--------|--------|--------|--------|--------------|
| Tacotron2 | BSD 3-Clause License | https://github.com/NVIDIA/tacotron2| https://arxiv.org/pdf/1712.05884| https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/nvidia_deeplearningexamples_tacotron2.ipynb This model is faster than real time, uses mel-spectrograms, which can be very fast. But it sounds really terrible compared to recent models. Probably not usable. |
| Hifi-GAN | MIT License | https://github.com/jik876/hifi-gan | https://arxiv.org/abs/2010.05646 | https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/nvidia_deeplearningexamples_hifigan.ipynb#scrollTo=b3b54df5 Old, but this have been used by many of papers. Sounds better than tacotron but not by much|
| FastSpeech2 |  
| VITS |  
| VALLE |
| NaturalSpeech2 |
| Jets |
| MELLE | 
| VALLE-2 | | | | Tried this using Amphion. It is not about to pronounces "Ichigo" and "AI" properly. Probably something went wrong with the phoneme conversion. E2/F5-TTS is abit better at this. |
| Voicebox |
| E2/F5-TTS | MIT License | https://github.com/SWivid/F5-TTS | arxiv.org/abs/2410.06885| https://huggingface.co/spaces/mrfakename/E2-F5-TTS  Generation seems pretty good, but not sure if it will be fast enough. Needs transcript of the reference text, F5-TTS needs speed set to 0.8 for better generation. |

**Comment by tikikun** [comment]
Why the sample on f5--ts work, it seems everything else is pretty bad

**Comment by hahuyhoang411** [comment]
<img width="1288" alt="Screenshot 2024-10-21 at 08 37 10" src="https://github.com/user-attachments/assets/a5f38396-5d8d-4efa-9dd5-885663b01f8a">

with f5 we can change the system prompt of Ichigo a bit and make it more nature

**Comment by PodsAreAllYouNeed** [comment]
Tested on TTS Arena and added to Drive:

**Commercial**
ElevenLabs
FishSpeech v1.4
PlayHT2.0
PlayHT3.0mini

**Non-Commercial**
[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS?tab=MIT-1-ov-file#readme) (MIT License)
[MeloTTS](https://github.com/myshell-ai/MeloTTS) (MIT License) (Multi-lingual, multi-accent)
[OpenVoicev2](https://github.com/myshell-ai/OpenVoice) (MIT License)
[Parler-TTS and Parler TTS Large](https://github.com/huggingface/parler-tts/tree/main?tab=Apache-2.0-1-ov-file#readme)(Apache-2.0)
[StyleTTS2](https://github.com/yl4579/StyleTTS2) (MIT License)

**Comment by PodsAreAllYouNeed** [comment]
After testing these models, it seems F5-TTS is the only open-source TTS that can get the pronunciation of both "Ichigo" and reading out of the acronym "AI" correct. The commercial ones have no problem with this of course. The next question is then whether F5-TTS inference is going to be fast enough. Will update after some testing.

**Comment by tikikun** [comment]
f5-tts vram usage is quite concerning, can you make a direct comparison with fishspeech

**Comment by PodsAreAllYouNeed** [comment]
I used nvtop to monitor F5-tts on my machine. Based on their provided inference script, its requiring 15GB of GPU memory. However, the model itself it only 1.35GB, so I will see if there is some room for optimization.

**Comment by tikikun** [comment]
15gb is nut

**Comment by PodsAreAllYouNeed** [comment]
> 15gb is nut

Sorry before I edited I said 15GB, but was an error on my part. Someone else's job didn't clear the GPU and it was sitting on 15GB.

**Comment by tikikun** [comment]
@bachvudinh you can double check the above result and give me the few best results with the latency and we can make some decisions

**Comment by tikikun** [comment]
Hi i think we need not to do the decoding, after a second audit i found F5-tts is so good for simply just do TTS, I will take over the implementation.

**Comment by tikikun** [comment]
Current progress:
MLX example:
- https://github.com/tikikun/f5-tts-mlx-quantized/

Can be used for MacOS

Pytorch:
- [tbu]

**Comment by hahuyhoang411** [comment]
marked as done. We will go with Fish for now and F5 later.
